[package]
name = "hn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.28.2"
reqwest = { version = "0.11.16", features = ["blocking"] }
substring = "1.4.5"
terminal_size = "0.2.6"
